name: Run Robot Framework with Qase.io

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Robot Framework tests with Qase.io
        env:
          QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
          QASE_PROJECT_CODE: "PRJCT"  # Replace with your Qase.io project code
        run: |
          if [ -d "project/tests/test-qase.robot" ]; then
            robot --listener qase.robotframework.Listener project/tests/test-qase.robot
          else
            echo "❌ ERROR: Folder 'project/tests/test-qase.robot' not found!" && exit 1
          fi

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-results
          path: output.xml
