name: Run Robot Framework with Qase.io

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Bisa diganti dengan windows-latest atau macos-latest jika perlu

    steps:
      # 1️⃣ Jalankan tes dengan listener Qase
      - name: Run Robot Framework tests
        env:
          QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}  # Pastikan token ada di GitHub Secrets
          QASE_PROJECT_CODE: "PRJCT"  # Ganti dengan kode project Qase Anda
        run: |
          robot --listener qase.robotframework.Listener tests/

      # 2️⃣  Simpan hasil tes sebagai artifact
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-results
          path: output.xml  # Bisa juga log.html dan report.html


      
